name: Lint Test and Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

jobs:
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test

jobs: 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build

